# Generated by Django 3.2 on 2022-12-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221215_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['pub_date', 'review'], 'verbose_name': 'Комментарий к отзыву', 'verbose_name_plural': 'Комментарии к отзыву'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['pub_date', 'titles'], 'verbose_name': 'Отзыв на произведение', 'verbose_name_plural': 'Отзывы на произведение'},
        ),
        migrations.RemoveField(
            model_name='titles',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='titles',
            name='rating',
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.TextField(max_length=256),
        ),
    ]
