# Generated by Django 3.2 on 2022-12-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20221216_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genrestitles',
            options={'verbose_name': 'Произведение:Жанры', 'verbose_name_plural': 'Произведения:Жанры'},
        ),
    ]
