# Generated by Django 3.2 on 2022-12-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_titles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['pub_date', 'title'], 'verbose_name': 'Отзыв на произведение', 'verbose_name_plural': 'Отзывы на произведение'},
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='titles',
            new_name='title',
        ),
    ]
