# Generated by Django 3.2 on 2022-12-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20221217_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ['-id'], 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.TextField(max_length=256),
        ),
    ]
